# 配置
#   密钥 NPM_TOKEN

name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Deps
        run: corepack enable && yarn

      - name: Build
        run: yarn run build

      - name: Authenticate with Registry
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ./.npmrc
          npm whoami          

      - name: Publish to npm
        run: npm publish
